name: Build for Release

on:
  release:
    types:
      - created

jobs:
  release:
    name: Build V8 using ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            build_script: ./scripts/build-v8.sh
          - os: macos-latest
            platform: mac
            build_script: ./scripts/build-v8.sh
          - os: ubuntu-latest
            platform: android
            build_script: ./scripts/build-v8.sh
          - os: macos-latest
            platform: ios
            build_script: ./scripts/build-v8.sh
          - os: windows-latest
            platform: win
            build_script: cmd.exe /C .\scripts\build-v8.bat

    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Build V8
        id: build
        run: ${{ matrix.build_script }} ${{ matrix.platform }} ${{ github.event.release.tag_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "${{ steps.build.outputs.package }}"
          path: package

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_GITHUB_TOKEN }}"
        with:
          upload_url: "${{ github.event.release.upload_url }}"
          asset_path: "${{ steps.build.outputs.package_path }}"
          asset_name: "${{ steps.build.outputs.package }}.tar.gz"
          asset_content_type: application/gzip
